name = "sentimentalica-etsy-feed"
main = "worker.js"
compatibility_date = "2026-05-28"
account_id = "f8ad0de6193a285dec8719ac848a991c"

[vars]
SHOP_ID = "17787065"
# ETSY_API_KEY is set as a secret: wrangler secret put ETSY_API_KEY
