#!/usr/bin/env python3
"""Assemble the approved 2026-10-03 evergreen article batch."""
from pathlib import Path
import shutil
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
STAGE = ROOT / "staging/overnight/assets"
GEN = Path("/Users/kseniateter/.codex/generated_images/01a0fdcb-5503-7302-8eda-20e32c917b0f")

ARTICLES = [
    dict(slug="how-to-keep-one-ordinary-weekday-without-documenting-everything", title="How to Keep One Ordinary Weekday Without Documenting Everything", category="Memory Keeping", excerpt="A gentle way to preserve one ordinary weekday through a single trace, one sentence, and one small page.", listing="4577423256", heading="Make the page with Morning Cup", bridge="Choose Morning Cup when the memory lives around breakfast, a coffee break, or the kitchen table. Its warm café imagery gives the page a coherent beginning while your receipt, date, and sentence keep the memory personal.", image="exec-083ab8a2-317c-4530-aa43-6682ce6a15e2.png", subject="an ordinary weekday", trace="a grocery receipt, tea label, bus ticket, or the corner of a paper bag", place="the kitchen table", color="oatmeal, moss, and warm brown"),
    dict(slug="how-to-write-about-a-hard-day-without-turning-it-into-an-essay", title="How to Write About a Hard Day Without Turning It Into an Essay", category="Gentle Journaling", excerpt="A small, contained journaling method for naming a difficult day without explaining every part of it.", listing="4506313481", heading="Give the reflection a quiet floral frame", bridge="Use Solace Bloom when you want the page to feel held rather than heavily decorated. Its restrained florals and devotional vintage mood create a calm border for one honest paragraph without asking you to make the difficult day look pretty.", image="exec-771e4d55-24e7-4d57-862c-38e72bd87d24.png", subject="a difficult day", trace="one phrase you remember, a weather note, or a plain scrap in the color of the room", place="a quiet evening desk", color="ink blue, parchment, and muted plum"),
    dict(slug="a-five-minute-bedside-journal-ritual-for-tired-nights", title="A Five-Minute Bedside Journal Ritual for Tired Nights", category="Creative Rituals", excerpt="A five-minute bedside ritual that keeps a journal close without turning the end of the day into another task.", listing="4568645714", heading="Let Dream Collage hold the stranger details", bridge="Choose Dream Collage when the day ends in fragments, odd images, or half-remembered dreams. Its surreal vintage textures give those loose details a visual home, while the five-minute ritual keeps the writing simple and restful.", image="exec-07d9c749-19d3-413a-85df-eb4453091769.png", subject="a tired evening", trace="a bedside note, a book mark, or one word copied from the day", place="the bedside table", color="dusty lavender, cream, and warm wood"),
    dict(slug="how-to-make-a-walk-memory-page-from-one-small-trace", title="How to Make a Walk Memory Page From One Small Trace", category="Memory Keeping", excerpt="Turn one leaf, ticket, or tiny observation from a walk into a quiet journal page with a clear sense of place.", listing="4525676610", heading="Build the page with Fern Hollow", bridge="Make it with Fern Hollow when your walk memory belongs to moss, trees, mushrooms, or damp woodland paths. The collection supplies a cohesive forest ground so one real leaf, route note, and remembered detail can remain the heart of the page.", image="exec-6d9e420c-7730-4a0f-a5f4-f7d13c1b3afd.png", subject="a neighborhood walk", trace="one fallen leaf, seed pod, ticket, or quick route sketch", place="an entryway table after the walk", color="moss, flax, stone, and faded rust"),
    dict(slug="how-to-journal-a-memory-you-can-hear-but-cannot-picture", title="How to Journal a Memory You Can Hear but Cannot Picture", category="Memory Keeping", excerpt="A practical way to preserve a remembered voice, song, or household sound when no photograph exists.", listing="4516818567", heading="Give sound a naturalist visual language", bridge="Choose Birdsong Vale when the memory begins with a voice, birds outside a window, or another sound you cannot photograph. Its feathers, aviary details, and dark naturalist mood provide visual rhythm without pretending to illustrate the exact moment.", image="exec-87db8cee-2b6f-4753-9312-56f2420c18fd.png", subject="a sound without a photograph", trace="a song title, a remembered phrase, or three words describing the sound", place="a window seat near an old radio", color="faded blue, sage, cream, and walnut"),
    dict(slug="how-to-return-to-an-unfinished-journal-page-without-starting-over", title="How to Return to an Unfinished Journal Page Without Starting Over", category="Junk Journal Tutorials", excerpt="A forgiving method for finishing an abandoned journal page without covering it up or beginning again.", listing="4488065121", heading="Use Blossom Gate for a gentle second layer", bridge="Use Blossom Gate when an unfinished page needs light, color, and one cohesive botanical direction. Its spring florals make an easy supporting layer; keep the original marks visible so the repaired page still records where you first stopped.", image="exec-66506099-7e1b-4859-af40-1cf193adafd1.png", subject="an unfinished journal page", trace="the first scrap you glued, the pencil line you stopped at, or the note that no longer feels complete", place="a forgiving afternoon worktable", color="blush clay, cream, faded green, and warm wood"),
]

LISTING_ARTICLES = [
    dict(slug="antique-ledger-pages-for-a-family-history-journal", title="Antique Ledger Pages for a Family History Journal", category="Junk Journal Inspiration", excerpt="Use antique ledger pages to give names, dates, and small family facts a calm structure without making the journal feel formal.", listing="4568633117", heading="Begin with Ledger Neutral", bridge="Choose Ledger Neutral when you want family dates and fragments to feel connected before you have every story. Its authentic bookkeeping lines, worn paper, and handwritten marks create structure while leaving your own names, photographs, and corrections in charge.", image="exec-811439e5-9091-4c8a-a6e5-504fcb127def.png", source=Path("/Users/kseniateter/sentimentalica-pipeline/Sentimentalica_batches/Listing_batches/169/1013_Ledger_Neutral/Ledger Neutral"), pages=["Ledger_Neutral_084.jpg","Ledger_Neutral_109.jpg","Ledger_Neutral_175.jpg"], theme="Ledger Neutral"),
    dict(slug="a-vintage-travel-journal-that-begins-before-the-trip", title="A Vintage Travel Journal That Begins Before the Trip", category="Travel Journaling", excerpt="Start a travel journal before departure with one route, one expectation, and a pocket for the evidence that comes home.", listing="4568281740", heading="Set the route with Wander Far", bridge="Make the journal with Wander Far when maps, compasses, tickets, and old-world travel color fit the trip you are imagining. The collection gives the opening pages a shared visual direction, then your real route and saved evidence take over.", image="exec-377847eb-832b-4dae-8c37-a4632e40b276.png", source=Path("/Users/kseniateter/sentimentalica-pipeline/Sentimentalica_batches/Listing_batches/043/258_Wander_Far/Wander Far"), pages=["Wander_Far_083.jpg","Wander_Far_103.jpg","Wander_Far_118.jpg"], theme="Wander Far"),
    dict(slug="a-quiet-log-cabin-journal-theme-for-nature-notes", title="A Quiet Log Cabin Journal Theme for Nature Notes", category="Junk Journal Inspiration", excerpt="Build a woodland journal around timber, pine, field notes, and the small seasonal changes you actually notice.", listing="4567220885", heading="Build the woodland base with Log Cabin", bridge="Choose Log Cabin when you want pine, timber, mountain water, and handmade-country warmth to belong together from the first page. Its watercolor imagery supplies the setting while your own weather notes and found details make the journal specific.", image="exec-968a80be-9a38-49a9-a4c5-63e4069f786c.png", source=Path("/Users/kseniateter/sentimentalica-pipeline/Sentimentalica_batches/Listing_batches/041/246_Log_Cabin/Log Cabin"), pages=["Log_Cabin_001.jpg","Log_Cabin_050.jpg","Log_Cabin_109.jpg"], theme="Log Cabin"),
    dict(slug="a-colorful-dog-memory-journal-that-still-feels-grown-up", title="A Colorful Dog Memory Journal That Still Feels Grown-Up", category="Memory Keeping", excerpt="Use clear color roles, ordinary photographs, and specific details to make a joyful dog memory journal without cartoon clutter.", listing="4570186359", heading="Give joyful dog memories one visual family", bridge="Use Dog Crew when bright color suits the dog you are remembering and you want florals, tags, collars, and playful watercolor details to coordinate. Keep real photographs and specific stories central; the collection supplies energy and connection around them.", image="exec-a9ed802e-ba2a-4145-905c-3fd858948557.png", source=Path("/Users/kseniateter/sentimentalica-pipeline/Sentimentalica_batches/Listing_batches/050/295_Dog_Crew/Dog Crew"), pages=["Dog_Crew_004.jpg","Dog_Crew_045.jpg","Dog_Crew_047.jpg"], theme="Dog Crew"),
]

def lead_body(a):
    return f'''<p class="lead">You do not need a complete record to keep {a['subject']}. A useful page can begin with one physical trace, one sentence, and a little room around both. The small format protects the memory from becoming another project you have to finish perfectly.</p>
<img src="./gen1.jpg" alt="Atmospheric {a['place']} in {a['color']}" loading="lazy">
<h2>Choose the part that still has texture</h2><p>Before reaching for decoration, ask what you can still sense. Notice the light, temperature, background sound, or object your attention keeps returning to. Write those details as plain notes. They are often more truthful than a polished summary, and they give the page a place to stand.</p>
<p>Choose {a['trace']}. If the original is private, fragile, or too bulky, copy its shape or color instead. The goal is not to archive everything. It is to give the memory one piece of evidence that feels connected to real life.</p>
<h2>Write one sentence with a clear edge</h2><p>Use a sentence that begins with “I noticed,” “I kept thinking about,” or “The part I want to remember is.” Stop when the sentence has named one thing. You can add more later, but a contained first line prevents the page from demanding an explanation of the entire day.</p>
<p>Place the sentence on a separate scrap rather than writing across the whole background. A small writing area makes the words feel intentional and leaves you free to move them while the composition settles.</p>
<h2>Build the page in three quiet layers</h2><p>Start with a plain or softly patterned foundation in {a['color']}. Add the physical trace next, then place the sentence where it can be read without lifting another element. Repeat one color once on the opposite side of the page. That small echo is usually enough to make the arrangement feel complete.</p>
<p>Resist filling every gap. Empty paper is useful: it separates the memory from the decoration and gives the eye somewhere to rest. If the page feels unfinished, add a date, place, or tiny weather mark before adding another image.</p>
<h2>Make the page easy to revisit</h2><p>Leave one small flap, pocket, or blank line for something you may remember later. This is not an invitation to postpone finishing; it is a gentle acknowledgement that memory arrives in pieces. Write the date on the back of the movable piece so it cannot become an anonymous scrap.</p>
<p>When you return, add only information that sharpens the original moment. A forgotten name, exact color, or small correction belongs. A long explanation added from obligation usually does not. The page can remain modest and still be complete.</p>
<h2>Finish with a detail only you would know</h2><p>Add one fact that could not come from a generic prompt: the cup you used, the wrong turn, the sentence someone always says, or the sound of a particular door. Specificity is what turns pretty paper into memory keeping. It does not need to be dramatic to be worth preserving.</p>
<p>Close the journal and return tomorrow. If the page still reads clearly from a small distance, leave it alone. A restrained page can hold a large feeling without explaining it away.</p>
<p>Find more gentle ways to keep ordinary life in <a href="../blog.html">the Sentimentalica journal archive</a>.</p>'''

def listing_body(a):
    return f'''<p class="lead">A strong themed journal does not come from using every image at once. It comes from choosing a small visual vocabulary, repeating it calmly, and leaving enough open space for real notes and memories. {a['theme']} offers a coherent starting world without deciding what your finished journal must say.</p>
<img src="./gen1.jpg" alt="Atmospheric scene inspired by the {a['theme']} palette" loading="lazy">
<h2>Begin with three real pages, not a pile</h2><p>Choose one page for structure, one for atmosphere, and one for small details. Look at them together before printing more. The strongest page should set the scale and mood; the quieter pages can become pockets, writing cards, borders, or narrow echoes elsewhere in the journal.</p>
<div class="kit-carousel" aria-label="Real pages from the {a['theme']} collection"><img src="./page1.jpg" alt="Real {a['theme']} printable page one" loading="lazy"><img src="./page2.jpg" alt="Real {a['theme']} printable page two" loading="lazy"><img src="./page3.jpg" alt="Real {a['theme']} printable page three" loading="lazy"></div>
<h2>Let the artwork choose the palette</h2><p>Pull one dark anchor, one clean paper light, one supporting middle color, and one distinctive accent from each page. These roles are more useful than a list of every color present. Use the anchor sparingly, repeat the light generously, and let the accent appear in only two or three small places.</p>
<div class="image-row"><img src="./palette1.jpg" alt="Color palette sampled from a real {a['theme']} page" loading="lazy"><img src="./palette2.jpg" alt="Second color palette sampled from a real {a['theme']} page" loading="lazy"><img src="./palette3.jpg" alt="Third color palette sampled from a real {a['theme']} page" loading="lazy"></div>
<h2>Give each spread one practical job</h2><p>Before decorating, decide what the spread will hold: a date, a short story, a photograph, a list, or a pocket of small evidence. The job protects the page from becoming a display of supplies. Add imagery only when it helps frame, separate, or support that purpose.</p>
<p>Keep the largest artwork away from the exact center. A calm margin beside it creates a natural place for handwriting. If the source page is detailed, pair it with plain cream or lightly distressed paper rather than another equally busy print.</p>
<h2>Print a small test before committing</h2><p>Print one chosen page at reduced size or in draft quality, then test it beside the photograph, note, or found object you plan to keep. Screen color can feel louder than paper color, and a border that looks delicate on a monitor may dominate a small journal. The test shows whether the artwork is supporting your material or competing with it.</p>
<p>If the page feels too strong, crop a quieter section instead of lowering every color. If it feels flat, repeat the accent with thread, pencil, or a narrow tab. Small corrections preserve the character of the artwork while giving your own evidence priority.</p>
<h2>Repeat one shape to make the journal feel whole</h2><p>A label, narrow tab, rounded corner, or torn vertical strip can travel through several pages. Repetition is quieter than adding more themed objects, and it makes even pages created weeks apart feel related. Change the material while keeping the shape familiar.</p>
<p>Add your own evidence last. A real name, route, weather note, photograph, or remembered phrase should remain the most specific thing on the page. Printable art gives the journal a world; the detail only you can supply gives it a reason to exist.</p>
<p>Before calling the spread finished, cover the decorative layers with your hand and read only the personal material. If the date, sentence, or photograph still carries the page, the balance is right. If the memory disappears, remove one ornamental piece and give the evidence more space.</p>
<p>Browse more grounded themes and practical page methods in <a href="../blog.html">the Sentimentalica journal archive</a>.</p>'''

def front(a, body):
    return f'''---\ntitle: {a['title']}\ncategory: {a['category']}\nexcerpt: {a['excerpt']}\ndate: 2026-10-03\nthumb: ./gen1.jpg\nrelated_ids: {a['listing']}\nrelated_heading: {a['heading']}\nrelated_text: {a['bridge']}\n---\n{body}\n'''

def main():
    for a in ARTICLES + LISTING_ARTICLES:
        d = STAGE / a['slug']; d.mkdir(parents=True, exist_ok=True)
        scene = Image.open(GEN / a['image']).convert('RGB')
        scene.thumbnail((1000, 1500), Image.Resampling.LANCZOS)
        scene.save(d / 'gen1.jpg', 'JPEG', quality=88, optimize=True, progressive=True)
        if 'source' in a:
            for i, name in enumerate(a['pages'], 1):
                shutil.copy2(a['source'] / name, d / f'page{i}.jpg')
        (d / 'post.html').write_text(front(a, listing_body(a) if 'source' in a else lead_body(a)))
        print(d / 'post.html')

if __name__ == '__main__': main()
